// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZyFlKRJYlZLu3aXoyrezXsYG2e_16yhA',
    appId: '1:977573047128:web:2f448b58a10159546e932d',
    messagingSenderId: '977573047128',
    projectId: 'zakahapp-194c7',
    authDomain: 'zakahapp-194c7.firebaseapp.com',
    storageBucket: 'zakahapp-194c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVG8xkAQbbsbqWZtZwMwSYEBtZEIsRtE8',
    appId: '1:977573047128:android:25816bb50b28f6836e932d',
    messagingSenderId: '977573047128',
    projectId: 'zakahapp-194c7',
    storageBucket: 'zakahapp-194c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9pROoRvGgrxfimpsHEbR5gTNpJ2F4bM',
    appId: '1:977573047128:ios:bcd3044f8568a02f6e932d',
    messagingSenderId: '977573047128',
    projectId: 'zakahapp-194c7',
    storageBucket: 'zakahapp-194c7.appspot.com',
    iosClientId: '977573047128-shfijseensch5ci9lqpqkqfvi4qc5sbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb9pROoRvGgrxfimpsHEbR5gTNpJ2F4bM',
    appId: '1:977573047128:ios:bcd3044f8568a02f6e932d',
    messagingSenderId: '977573047128',
    projectId: 'zakahapp-194c7',
    storageBucket: 'zakahapp-194c7.appspot.com',
    iosClientId: '977573047128-shfijseensch5ci9lqpqkqfvi4qc5sbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2',
  );
}
